//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoItem
    {
        public System.Guid itemId { get; set; }
        public string itemName { get; set; }
        public string itemDescription { get; set; }
        public System.DateTime itemDeadline { get; set; }
        public string itemStatus { get; set; }
        public System.DateTime itemCreateDate { get; set; }
        public System.Guid listId { get; set; }
        public bool isEligible { get; set; }
    
        public virtual ToDoList ToDoList { get; set; }
    }
}
