//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListApp.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToDoList()
        {
            this.ToDoItems = new HashSet<ToDoItem>();
        }
    
        public System.Guid listId { get; set; }
        public string listName { get; set; }
        public System.Guid userId { get; set; }
        public System.DateTime listCreateDate { get; set; }
        public bool isEligible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDoItem> ToDoItems { get; set; }
        public virtual User User { get; set; }
    }
}
